// Code generated by "enumer -type=ChangeType -json"; DO NOT EDIT.

//
package typhon4g

import (
	"encoding/json"
	"fmt"
)

const _ChangeTypeName = "ChangeTypeModifyChangeTypeNewChangeTypeDeleted"

var _ChangeTypeIndex = [...]uint8{0, 16, 29, 46}

func (i ChangeType) String() string {
	if i < 0 || i >= ChangeType(len(_ChangeTypeIndex)-1) {
		return fmt.Sprintf("ChangeType(%d)", i)
	}
	return _ChangeTypeName[_ChangeTypeIndex[i]:_ChangeTypeIndex[i+1]]
}

var _ChangeTypeValues = []ChangeType{0, 1, 2}

var _ChangeTypeNameToValueMap = map[string]ChangeType{
	_ChangeTypeName[0:16]:  0,
	_ChangeTypeName[16:29]: 1,
	_ChangeTypeName[29:46]: 2,
}

// ChangeTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ChangeTypeString(s string) (ChangeType, error) {
	if val, ok := _ChangeTypeNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ChangeType values", s)
}

// ChangeTypeValues returns all values of the enum
func ChangeTypeValues() []ChangeType {
	return _ChangeTypeValues
}

// IsAChangeType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ChangeType) IsAChangeType() bool {
	for _, v := range _ChangeTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ChangeType
func (i ChangeType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ChangeType
func (i *ChangeType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ChangeType should be a string, got %s", data)
	}

	var err error
	*i, err = ChangeTypeString(s)
	return err
}
